
title: YZ
description: >- # this means to ignore newlines until "baseurl:"
  主页
baseurl: "" # the subpath of the site
url: "https://yz14.github.io" # the base hostname & protocol for the site
og_image: /assets/img/yz.png
google_analytics: "UA-121636368-3"

# header:
#   pages:
#     # - name: 心理学
#     #   slug: /main/docs/psy
#     # - name: 机器学习
#     #   slug: /main/docs/ml
#     # - name: 深度学习
#     #   slug: /main/docs/dl
#     # - name: 随笔
#     #   slug: /main/docs/zw

footer:
  show_powered_by: true
  contact:
    - name: Email
      value: E-mail
      link: mailto:1163660010@qq.com
    - name: WeChat
      value: WeChat
      link: "#"
#   follow:
#     - name: Twitter
#       link: http://twitter.com/YourTwitterUsername
#       username: "@YourTwitterUsername"
#     - name: Facebook
#       link: http://facebook.com/YourFacebookUsername
#     - name: LinkedIn
#       link: http://linkedin.com/in/YourLinkedInUsername
#     - name: GitHub
#       link: http://yz14.github.io
#     - name: Dribbble
#       link: https://dribbble.com/YourDribbbleUsername
#     - name: RSS
#       link: /feed.xml

# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
