# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: YZ
description: >- # this means to ignore newlines until "baseurl:"
  主页
baseurl: "/tm28" # the subpath of the site
url: "https://yz14.github.io" # the base hostname & protocol for the site
og_image: /assets/img/yz2.jpg
google_analytics: "UA-121636368-3"

header:
  pages:
    - name: 主页
      slug: /
    - name: 博客
      slug: /blog
    - name: 生活

footer:
  show_powered_by: true
  contact:
    - name: Email
      value: 发送邮件
      link: mailto:1163660010@qq.com
    - name: WeChat
      value: 二维码
      link: "#"
#   follow:
#     - name: Twitter
#       link: http://twitter.com/YourTwitterUsername
#       username: "@YourTwitterUsername"
#     - name: Facebook
#       link: http://facebook.com/YourFacebookUsername
#     - name: LinkedIn
#       link: http://linkedin.com/in/YourLinkedInUsername
#     - name: GitHub
#       link: http://yz14.github.io
#     - name: Dribbble
#       link: https://dribbble.com/YourDribbbleUsername
#     - name: RSS
#       link: /feed.xml

# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
